#!/bin/bash

while IFS= read -r file_name
do 
	codesign -f -o runtime -s 'Developer ID Application: University College London (8UMT23UD55)' "dist/TACA.app/Contents/${file_name}" --entitlements entitlements.plist
done < unsigned_dylibs.txt